ENVIRONMENT: "local"
SERVER_PORT: "8080"
SERVLET_CONTEXT_PATH: "/billing/router-or"
MS_NAME: "billing-router-or"
FAMILY_POSTGRES_HOST: "default-rds-write.mx.dev.soytul.com"
FAMILY_POSTGRES_PASSWORD: "n8br2u7ypiu1yeza"
COUNTRY: "MX"
LOCALE: "es_mx"

SHARED_CONFIG_SERVER_URL: "https://internal.dev.soytul.com/shared/config-server"
LOGISTIC_ROUTING_URL: "https://internal.dev.soytul.com/logistic/routing"
LOGISTIC_PACKAGE_URL: "https://internal.dev.soytul.com/logistic/package"
SALE_BILLING_FACTURAMA_URL: "https://internal.dev.soytul.com/sale/billing-facturama"
SALE_BILLING_DATAICO_URL: "https://internal.dev.soytul.com/sale/billing-dataico"